from django.shortcuts import render, redirect, get_object_or_404
from .models import Essay, Evaluation, Student
from .forms import EssaySubmissionForm
from .mock_evaluator import MockEvaluator
import io
import pypdf
from docx import Document

def dashboard(request):
    # Fetch recent evaluations (AI) for the dashboard
    evaluations = Evaluation.objects.filter(evaluator_type='AI').select_related('essay__student').order_by('-created_at')[:10]
    students = Student.objects.all()
    
    # Calculate mock class mastery
    total_score = 0
    scored_count = 0
    support_needs = set()
    
    for ev in evaluations:
        if ev.overall_band:
            total_score += float(ev.overall_band)
            scored_count += 1
            if float(ev.overall_band) < 6.0:
                support_needs.add(ev.essay.student)
                
    class_mastery = round(total_score / scored_count, 1) if scored_count > 0 else 0

    context = {
        'evaluations': evaluations,
        'students': students,
        'class_mastery': class_mastery,
        'support_needs': list(support_needs),
    }
    return render(request, 'ielts_engine/dashboard.html', context)

def submit_essay(request):
    if request.method == 'POST':
        form = EssaySubmissionForm(request.POST, request.FILES)
        scenario = request.POST.get('scenario', 'standard')
        
        if form.is_valid():
            essay = form.save(commit=False)
            
            # Handle Student Lookup or Creation by identifier (Name or ID)
            identifier = form.cleaned_data['student_identifier']
            student = None
            
            # Try lookup by ID first if numeric
            if identifier.isdigit():
                student = Student.objects.filter(id=int(identifier)).first()
            
            # Fallback to lookup by Name
            if not student:
                student = Student.objects.filter(name__iexact=identifier).first()
            
            # Create if not found (Simple implementation)
            if not student:
                student = Student.objects.create(name=identifier)
            
            essay.student = student
            
            # Handle uploaded file extraction
            uploaded_file = request.FILES.get('uploaded_file')
            if uploaded_file:
                extracted_text = ""
                file_name = uploaded_file.name.lower()
                
                try:
                    if file_name.endswith('.pdf'):
                        pdf_reader = pypdf.PdfReader(io.BytesIO(uploaded_file.read()))
                        for page in pdf_reader.pages:
                            text = page.extract_text()
                            if text:
                                extracted_text += text + "\n"
                    elif file_name.endswith('.docx') or file_name.endswith('.doc'):
                        doc = Document(io.BytesIO(uploaded_file.read()))
                        for para in doc.paragraphs:
                            extracted_text += para.text + "\n"
                except Exception:
                    pass
                
                if extracted_text.strip():
                    essay.extracted_text = extracted_text.strip()
            
            essay.save()
            
            # Create AI Evaluation
            evaluator = MockEvaluator()
            results = evaluator.evaluate(essay.extracted_text, scenario)
            
            Evaluation.objects.create(
                essay=essay,
                evaluator_type='AI',
                task_achievement=results['task_response'],
                coherence_cohesion=results['coherence_cohesion'],
                lexical_resource=results['lexical_resource'],
                grammar_accuracy=results['grammatical_range_accuracy'],
                overall_band=results['overall_band'],
                feedback_comments="Generated by SayarDesk AI"
            )
            
            return redirect('evaluation_view', essay_id=essay.id)
    else:
        form = EssaySubmissionForm()
    
    return render(request, 'ielts_engine/submission_form.html', {'form': form})

def evaluation_view(request, essay_id):
    essay = get_object_or_404(Essay, id=essay_id)
    
    # Get evaluations
    ai_eval = essay.evaluations.filter(evaluator_type='AI').first()
    teacher_eval = essay.evaluations.filter(evaluator_type='TEACHER').first()
    
    # Active evaluation for UI defaults
    evaluation = teacher_eval if teacher_eval else ai_eval
    
    # Mocking errors for the UI display based on score (simulating real backend)
    evaluator = MockEvaluator()
    if evaluation and float(evaluation.overall_band or 0) >= 7.5:
        scenario = 'high_performing'
    elif evaluation and float(evaluation.overall_band or 0) <= 5.0:
        scenario = 'at_risk'
    else:
        scenario = 'standard'
        
    results = evaluator.evaluate(essay.extracted_text, scenario)
    
    context = {
        'essay': essay,
        'ai_eval': ai_eval,
        'teacher_eval': teacher_eval,
        'evaluation': evaluation,  # Current active one
        'errors': results['errors'],
        'results': results
    }
    return render(request, 'ielts_engine/evaluation.html', context)

def submit_override(request, essay_id):
    if request.method == 'POST':
        essay = get_object_or_404(Essay, id=essay_id)
        
        # Get or create Teacher evaluation
        evaluation, created = Evaluation.objects.get_or_create(
            essay=essay,
            evaluator_type='TEACHER'
        )
        
        # Update scores from post data
        evaluation.task_achievement = request.POST.get('task_achievement')
        evaluation.coherence_cohesion = request.POST.get('coherence_cohesion')
        evaluation.lexical_resource = request.POST.get('lexical_resource')
        evaluation.grammar_accuracy = request.POST.get('grammar_accuracy')
        evaluation.feedback_comments = request.POST.get('feedback_comments', '')
        
        # Re-calculate overall band (handled in model save)
        evaluation.overall_band = None 
        evaluation.save()
        
        return redirect('evaluation_view', essay_id=essay.id)
    
def student_progress(request, student_id):
    student = get_object_or_404(Student, id=student_id)
    essays = student.essays.all().order_by('submission_date')
    
    progress_data = []
    for essay in essays:
        # Get the 'best' evaluation for this essay (Teacher override if exists, else AI)
        eval = essay.evaluations.filter(evaluator_type='TEACHER').first() or \
               essay.evaluations.filter(evaluator_type='AI').first()
        
        if eval:
            progress_data.append({
                'date': essay.submission_date.strftime('%Y-%m-%d'),
                'score': float(eval.overall_band),
                'task': essay.task_type,
                'essay_id': essay.id
            })
            
    context = {
        'student': student,
        'progress_data': progress_data,
    }
    return render(request, 'ielts_engine/student_progress.html', context)
