# Generated by Django 5.2.11 on 2026-04-29 04:40

from django.db import migrations, models


def backfill_student_ids(apps, schema_editor):
    """Generate STU-XXXX IDs for all existing students."""
    Student = apps.get_model('ielts_engine', 'Student')
    for student in Student.objects.all().order_by('id'):
        student.student_id = f"STU-{student.id:04d}"
        student.save(update_fields=['student_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_engine', '0003_evaluation_shap_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        # Step 1: Add student_id WITHOUT unique constraint
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
            preserve_default=False,
        ),
        # Step 2: Backfill existing students
        migrations.RunPython(backfill_student_ids, migrations.RunPython.noop),
        # Step 3: Now enforce unique
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
